### ISSUE TITLE
Milestone 1 Initial Discussion

### ISSUE THREAD

**Issue by Lorraine97** [Lorraine97/prelim_eda_helper#1]
> Purpose: simplified feature comparison tool
> 
> Function 1: Numeric to numeric feature comparison
> - Scatter plot, trendline, highlight outliers (option)
> - Correlation
> - Number of outliers
> - P-value
> - Other important facts
> 
> Function 2: Numeric to categorical feature comparison
> - Histogram
> - Box-plot
> - Number of outliers
> - Other important facts
> 
> Function 3: Categorical to categorical feature comparison
> - Heatmap
> - Barchart
> 
> Function 4: Single feature
> - Detects feature variable type
> - Distribution plot
> - mean/ median/ std
> - Identify highly correlated features (threshold option)
> 
> 

Tasks:

- [ ] Name of the project: prelim_eda_helper
- [ ] Repo creation: Xinru
- [ ] edit CONTRIBUTORS.md : Morris
- [ ] edit CONDUCT.md: Xinru
- [ ] edit CONTRIBUTING.md with templates. factory_bot_rails's is pretty easy to follow: Mehwish
- [ ] edit REAMD.md: Austin

write complete docstrings

- [ ] Function 1 (Num vs Num): Austin
- [ ] Function 2 (Num vs Cat): Morris
- [ ] Function 3 (Cat vs Cat): Xinru
- [ ] Function 4 (Num [its own distribution]): Mehwish

- [ ] Build project boards: Morris

- [ ] Build Milestones (github function): Austin

- [ ] Branch protection: Xinru

Note: 
1. Branch name convention: {milestone number}-{branch name} (e.g m1-function1)

- [ ] Submission: Austin
